# Generated by Django 2.2.6 on 2019-11-04 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='textbook',
            name='Condition',
            field=models.CharField(choices=[('MINT', 'BRAND NEW'), ('LIKE_NEW', 'LIKE NEW'), ('DECENT', 'GOOD'), ('FAIR', 'FAIR'), ('POOR', 'POOR')], default='MINT', max_length=10),
        ),
    ]
