# Generated by Django 2.2.6 on 2019-11-04 00:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_textbook_condition'),
    ]

    operations = [
        migrations.RenameField(
            model_name='textbook',
            old_name='Year_Of_Publication',
            new_name='Date_Published',
        ),
    ]
